### PR TITLE
Fixes site baseurl for github

### PR DESCRIPTION
**Pull request by khafa100**
Corrected urls for links and assets to be configured correctly for baseurl

### CODE REVIEW

**Comment by tatwell** [comment]
Where's the link to the published Github site? I would expect to see that at the top of the README.

For example, see the previous style guide:

- https://github.com/chapmanu/web-components

**Comment by tatwell** [comment]
I recommend all devs, when you have a chance, clone this and try to set up locally following README.

**Comment by tatwell** [comment]
This is what I currently see:

screen shot 2017-07-13 at 8 43 53 am

What I'd like to see:

- Theme / styles applied. (Do you need to republish?)
- At least one working nav link. All nav links I click currently lead to 404 pages.

**Comment by khafa100** [comment]
This pull request will hopefully fix the site so that the theme and styles will be applied and that the links will work correctly. I realized after the initial launch that I forgot to add the baseurl's which resulted in what you're seeing right now.

As a note: I only have Typography and Color pages set up, the other three pages will lead to 404 pages. The 404 page isn't configured correctly yet either and I'm working on fixing that, but I wanted to have something up and running to show Wai in the mean time.

**Comment by tatwell** [comment]
I'd like to see the working product. Can you [publish using the gh-pages branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)?

Also, comment out the dead links (with a comment noting they will be added in future).

**Comment by khafa100** [comment]
As I understand it, I can only publish by merging to the master branch or through a `/docs` folder in the master branch repository. At least, those are the only options available to me in the settings.

**Comment by tatwell** [comment]
Looks good and I am able to install and run locally following README. But I'm not ready to approve this yet. I still need to look at code. 

And I'd like the home page to have some content, a brief overview, and I'd like to git back to the Github repo easily from the published pages.

**Comment by tatwell** [comment]
Before you delete this branch, please make the following changes:

- Stub out home page. Provide a brief overview with link to site's Github repo.
- Git rid of this [`_includes foo.html` pattern](https://github.com/chapmanu/smc-style-guide#adding-pages). HTML can be included in `_pages/page.md` files directly.
- Update `description` in config file. Should `url` be filled in?

**Pull request merged**
